application: myapplication
module: letsencrypt
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  BEARER_TOKEN: 'mysecrettoken'

handlers:
- url: /.*
  script: well_known.app